# Generated by Django 5.0 on 2023-12-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='order',
        ),
    ]
