# architect.yml
name: ecom-django
description: Despliegue de la aplicación Django con Docker y Architect
environments:
  local:
    debug: true
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-idcf^4be5qtns$3j!w-+#%5_j)r#(sri9b((@-yizeim_+9sc5
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
